modLoader="javafml"
loaderVersion="${forgeVersionRange}"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/PacketFixer"

[[mods]]
modId="packetfixer"
version="${modVersion}"
displayName="PacketFixer"
icon="icon.png"

authors="TonimatasDEV"
description='''
A simple mod to solve various problems with packets.
'''

[[dependencies.packetfixer]]
modId="forge"
mandatory=true
versionRange="${forgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.packetfixer]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"
