modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "Apache 2.0"

[[mods]]
modId = "packetsizedoubler"
version = "${mod_version}"
displayName = "PacketSizeDoubler"
authors = "TonimatasDEV"
description = '''
A simple mod for doubling the size of allowed packets.
'''

[[dependencies.packetsizedoubler]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.packetsizedoubler]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
