modLoader="javafml"
loaderVersion="[38,47)"
license="Apache License Version 2.0"

[[mods]]
modId="packetsizedoubler"
version="1.1.0"
displayName="PacketSizeDoubler"

authors="TonimatasDEV"
description='''
A simple mod for doubling the size of allowed packets.
'''

[[dependencies.packetsizedoubler]]
modId="forge"
mandatory=true
versionRange="[38,47)"
ordering="NONE"
side="BOTH"

[[dependencies.packetsizedoubler]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.21)"
ordering="NONE"
side="BOTH"
