modLoader="javafml"
loaderVersion="[${forgeVersionRange},)"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/PacketFixer/issues"

[[mods]]
modId="packetfixer"
version="${modVersion}"
displayName="Packet Fixer"
logoFile="icon.png"
updateJSONURL="https://api.modrinth.com/updates/packet-fixer/forge_updates.json"
authors="TonimatasDEV"
description='''
A simple mod to solve various problems with packets/NBT's.
'''

[[dependencies.packetfixer]]
modId="forge"
mandatory=true
versionRange="[${forgeVersionRange},)"
ordering="NONE"
side="BOTH"

[[dependencies.packetfixer]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"
