modLoader = "javafml"
loaderVersion = "[41,),[42,),[43,),[44,),[45,)"
license = "Apache License Version 2.0"

[[mods]]
modId = "packetsizedoublerforge"
version = "${file.jarVersion}"
displayName = "PacketSizeDoublerForge"

authors = "TonimatasDEV"
description = '''
A simple mod for doubling the size of allowed packets.
'''

[[dependencies.packetsizedoublerforge]]
modId = "forge"
mandatory = true
versionRange = "[41,),[42,),[43,),[44,),[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.packetsizedoublerforge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.4]"
ordering = "NONE"
side = "BOTH"
