modLoader = "javafml"
loaderVersion = "[32,)"
license = "All Rights Reserved"

[[mods]]
modId = "packetsizedoublerforge"
version = "1.0.1"
displayName = "PacketSizeDoublerForge"

authors = "TonimatasDEV"
description = '''
A simple mod for doubling the size of allowed packets.
'''

[[dependencies.packetsizedoublerforge]]
modId = "forge"
mandatory = true
versionRange = "[32,37)"
ordering = "NONE"
side = "BOTH"

[[dependencies.packetsizedoublerforge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,1.17)"
ordering = "NONE"
side = "BOTH"
