modLoader="javafml"
loaderVersion="${forge_version_range}"
license="Apache 2.0"

[[mods]]
modId="packetfixer"
version="1.1.0"
displayName="PacketFixer"

authors="TonimatasDEV"
description='''
A simple mod to solve various problems with packets.
'''

[[dependencies.packetfixer]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.packetfixer]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
