modLoader="javafml"
loaderVersion="${forge_version_range}"
license="MIT"

[[mods]]
modId="packetfixer"
version="${mod_version}"
displayName="PacketFixer"
icon="icon.png"

authors="TonimatasDEV"
description='''
A simple mod to solve various problems with packets.
'''

[[dependencies.packetfixer]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.packetfixer]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
