modLoader = "javafml"
loaderVersion = "[38,),[39,),[40,)"
license = "Apache License Version 2.0"

[[mods]]
modId = "packetsizedoublerforge"
version = "${file.jarVersion}"
displayName = "PacketSizeDoublerForge"

authors = "TonimatasDEV"
description = '''
A simple mod for doubling the size of allowed packets.
'''

[[dependencies.packetsizedoublerforge]]
modId = "forge"
mandatory = true
versionRange = "[38,),[39,),[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.packetsizedoublerforge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"
