modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache License 2.0"

[[mods]]
modId = "packetsizedoublerforge"
version = "${file.jarVersion}"
displayName = "PacketSizeDoublerForge"

authors = "TonimatasDEV"
description = '''
A simple mod for doubling the size of allowed packets.
'''

[[dependencies.packetsizedoublerforge]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.packetsizedoublerforge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2]"
ordering = "NONE"
side = "BOTH"
