---
name: Build
on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew clean mergedJar

      - name: Upload a Java 17 artifact
        uses: actions/upload-artifact@v4
        with:
          name: PacketFixer17
          path: packetfixer/java17/build/libs/**.jar

      - name: Upload a Java 21 artifact
        uses: actions/upload-artifact@v4
        with:
          name: PacketFixer21
          path: packetfixer/java21/build/libs/**.jar
