name: Java with Gradle

on:
  push:
    branches: [1.12.2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: "temurin"

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build jar

      - name: Upload a Forge Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PacketFixerForge
          path: forge/build/libs/**.jar