name: Java with Gradle

on:
  push:
    branches: [master]

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      repository-projects: write
      security-events: write
      statuses: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java JDK 8
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Build with Gradle
        run: chmod +x ./gradlew

      - name: Generate jar with Gradle
        run: ./gradlew exportAll

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: PerWorldPlugins
          path: artifacts/**.jar